name: 'Rspd Python Assignment Report'
description: 'Automatically grades submitted python code and sends it to the provided api'
icon: 'send'
color: 'purple'
inputs:
  api_url:
    description: 'the api to call after passing results'
    required: false
    default: 'http://host.docker.internal:3000/api/submission/github'
  repositoryUrl:
    description: 'the repositoryUrl of the actor'
    required: true
  repository:
    description: 'the repository of the actor'
    required: true
  actor:
    description: 'The user the submission is related to'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh'
