name: 'Rspd Assignment Report'
description: 'Automatically grades submitted python code and sends it to the provided api'
branding: 
  icon: 'send'
  color: 'purple'
inputs:
  api_url:
    description: 'the api to call after passing results'
    required: false
    default: 'http://host.docker.internal:3000/api/github/submission'
  repositoryUrl:
    description: 'the repositoryUrl of the actor'
    required: true
  repository:
    description: 'the repository of the actor'
    required: true
  actor:
    description: 'The user the submission is related to'
    required: true
runs:
  using: 'composite'
  steps:
    - run: chmod +x ${{ github.action_path }}/setup.sh && ${{ github.action_path }}/setup.sh
      shell: bash
    - run: pytest --json-report -v --json-report-indent=2
      shell: bash
    - run: chmod +x ${{ github.action_path }}/api-request.py && ${{ github.action_path }}/api-request.py
      shell: bash
      if: always
      env:
        API_URL: ${{ inputs.api_url }}
        REPO_URL: ${{ inputs.repositoryUrl }}
        REPO: ${{ inputs.repository }}
        ACTOR: ${{ inputs.actor }}