name: GitHub Classroom Workflow

on:
  push:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cache: [false]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 'david_schmidt_privat@outlook.com'
          password: 'Skywalker2001?'
      - uses: konsumgandalf/rspd-python-assignment-report@v1.1.0
        with:
          api_url: 'http://example-api.com/submission/github'
          repositoryUrl: 'git://github.com/OTH-Digital-Skills/lab-04-mario-angie_123'
          actor: 'angie_123'
          repository: 'OTH-Digital-Skills/lab-04-mario-angie_123'
