name: GitHub Classroom Workflow

on:
  push:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cache: [false]
    steps:
      - uses: actions/checkout@v2
      - name: Rspd Python Assignment Report
        uses: KonsumGandalf/rspd-assignment-grader@v4
        with:
          repositoryUrl: 'git://github.com/OTH-Digital-Skills/lab-04-mario-angie_123'
          actor: 'angie_123'
          repository: 'OTH-Digital-Skills/lab-04-mario-angie_123'