name: GitHub Classroom Workflow

on:
  push:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cache: [false]
    steps:
      - uses: actions/checkout@v2